/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef GFX_H_
# define GFX_H_
# define VAR_IRESOLUTION "v"
# define VAR_ISCALE "y"
# define VAR_ITIME "f"

const char *gfx_frag =
 "#version 130\n"
 "uniform float f;"
 "uniform vec2 v;"
 "uniform float y;"
 "const float x=acos(-1.);"
 "const vec2 m=vec2(1.,0.);"
 "float t(vec2 m)"
 "{"
   "return fract(sin(dot(m.xy,vec2(12.9898,78.233)))*43758.5);"
 "}"
 "float s(float f)"
 "{"
   "float v=-1.+2.*t(floor(f)*m.xx),y=-1.+2.*t(ceil(f)*m.xx);"
   "return mix(v,y,smoothstep(.25,.75,fract(f)));"
 "}"
 "float s(float f,float v,float y,float m)"
 "{"
   "float x=0.,a=1.;"
   "for(float r=v;r<y;r=r*2.)"
     "x=a*s(r*f)+x,a=a*m;"
   "return x;"
 "}"
 "vec2 s(vec2 m,float f)"
 "{"
   "return mat2(cos(f),sin(f),-sin(f),cos(f))*m;"
 "}"
 "mat3 n(vec3 f)"
 "{"
   "vec3 m=cos(f),s=sin(f);"
   "mat3 v=mat3(m.y*m.x,m.x*s.z+m.z*s.x*s.y,s.x*s.z-m.x*m.z*s.y,-m.y*s.z,m.x*m.z-s.x*s.y*s.z,m.z*s.x+m.x*s.y*s.z,s.y,-m.y*s.x,m.x*m.y);"
   "return v;"
 "}"
 "float n(vec2 f,vec2 x)"
 "{"
   "return length(max(abs(f)-x,0.));"
 "}"
 "vec3 t(float f,float m)"
 "{"
   "vec3 x=vec3(207.,30.,102.)/255.,s=vec3(245.,194.,87.)/255.;"
   "mat3 v=n(.5*m*vec3(1.1,1.3,1.5));"
   "return 1.1*mix(-cross(x,v*x),-(v*x),f);"
 "}"
 "void r(out vec4 r,in vec2 a)"
 "{"
   "vec2 c=a/v.yy-.5-.33*m.xy;"
   "c=n(c,.25*f);"
   "vec4 z=vec4(0.,m.yyy);"
   "float l=128.,i=.2;"
   "for(int u=0;u<12;++u)"
     "{"
       "c=n(c,1.1);"
       "vec2 d=vec2(length(c),atan(c.y/c.x)-float(u)*.1*f),g=vec2(d.x-.05*float(u),mod(d.y,2.*x/l)-x/l),o=vec2(i,g.y);"
       "float w=(d-g).y;"
       "i=.2+float(u)*.005+.006;"
       "float e=.1*s(w-f-4.*float(u),1.,100.,.45)+.05*t(w*m.xx+.2*m.yx)+.05*y,p=abs(.005*float(u)+e),h=abs(.015+.005*t(w*m.xx+.4));"
       "vec4 b=vec4(n(g-i*m.xy,p*m.xy+h*m.yx),t((g.x-i)/.05+g.y/2./x,f+sin(f+float(u))));"
       "z=mix(z,b,step(b.x,z.x));"
     "}"
   "vec3 u=z.yzw*step(z.x,0.);"
   "r=vec4(u,1.);"
 "}"
 "void main()"
 "{"
   "r(gl_FragColor,gl_FragCoord.xy);"
 "}";

#endif // GFX_H_
